### ISSUE TITLE
Unique 'issue' : Trading with custom villager with custommodeldata items

### ISSUE THREAD

**Issue by thomasdaley2** [bendy1234/FastTrading#1]
This is a unique issue thats not a fault of the mod but I remember that its wasnt an issue on the now abandoned EasierVillagerTrading.  I have a custom villager thats used to change and item (eg Cooked Pork) for a custom Taco (which is still cooked Pork).

When using your mod it keeps taking this items that are already altered (new texture) and trading them on a loop.  Im unsure HOW this could be fixed but thought I'd write here if maybe you had some ideas.

**Comment by bendy1234** [comment]
The mod uses Minecraft's autofill code. Minecraft only checks if the specifyed item component(s) are equal when trading. That means if the trade doesn't specify any item components it allows all items with the same item type to be traded just like what happend in your case. 


I can implement my own code to move the items into the slots that matches exactly.
